[book]
title = "tuidom"
authors = ["norpie"]
description = "A declarative TUI framework for Rust"
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/norpie/tuidom"
