[package]
name = "rafter"
version = "0.1.0"
edition = "2024"

[dependencies]
rafter-derive = { path = "../rafter-derive" }
ratatui = "0.29"
crossterm = "0.28"
tokio = { version = "1", features = ["full"] }
inventory = "0.3"
thiserror = "2"

[lints]
workspace = true
