[package]
name = "dataverse-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
rafter = { path = "../rafter" }
tuidom = { path = "../tuidom" }
tokio = { version = "1", features = ["full"] }
simplelog = "0.12"
log = "0.4"
inventory = "0.3"
